config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Root route
  root 'application#home'

  # Shallow nested routes, nests: index create new
  resources :dance_studios, except: %i[new index], shallow: true do
    resources :costumes
    resources :dancers, except: %i[create]
    resources :costume_assignments, only: %i[index]
    # Route for dance studio to view their current dancers
    get '/dancers/current_dancers' => 'dancers#current_dancers', as: 'current_dancers'
  end

  post '/dancers' => 'dancers#create'

  # Routes for a dancer
  scope '/dancers/:id' do
    # Route for dancers to view all their costume assignments
    get '/costume_assignments' => 'dancers#dancer_assignments', as: 'dancer_costumes'
    # Route for dancer to view their current costume asignments
    get '/current_assignments' => 'dancers#current_assignments', as: 'dancer_current_assignments'
  end

  # Routes for a dance studio
  scope '/dance_studios/:id' do
    # Route for dance studio to search for costume(s)
    get '/search' => 'dance_studios#search', as: 'search'
    # Route for dance studio to view their current costume assignments
    get '/current_assignments' => 'dance_studios#current_assignments', as: 'studio_current_assignments'
    # Route for dance studio to view the costumes currently in use
    get '/current_costumes' => 'dance_studios#current_costumes', as: 'studio_current_costumes'
    # Route for dance studio to view the costumes not currently in use
    get '/unassigned_costumes' => 'dance_studios#unassigned_costumes', as: 'unassigned_costumes'
  end
  scope '/costumes/:id' do
    # Routes for dance studio to assign a costume to dancers
    get '/assign' => 'costumes#assign_costume', as: 'assign_costume'
    post '/assign' => 'costumes#assign'
    # Route for a dance studio to view all of a costume's assignments
    get '/assignments' => 'costume_assignments#costume_assignments', as: 'assigned_costume'
    # Route for a dance studio to view a costume's season assignments
    get '/season_assignments' => 'costume_assignments#season_assignments', as: 'season_assignments'
    # Route for a dance studio to delete a costume's season assignments
    delete '/season_assignments' => 'costume_assignments#delete_season_assignments'
    # Routes for a dance studio to edit a costume's season assignments
    get '/edit_season_assignments' => 'costumes#edit_season_assignments', as: 'edit_season_assignments'
    patch '/edit_season_assignments' => 'costumes#update_season_assignments'
    post '/edit_season_assignments' => 'costumes#update_season_assignments'
  end

  # Route for signing up a user (dance_studio & dancer)
  get '/register' => 'registrations#new'

  # Routes for logging in
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  # Routes for Google authentication
  get 'auth/google_oauth2', as: 'google_omniauth'
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('application#home')
end

# You can have the root of your site routed with "root":
# root 'welcome#index'

# Example of regular route:
# get 'products/:id' => 'catalog#view'

# Example of Custom Route:
# get "students/:id/activate" => "students#activate", as: "activate_student"

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  before_action :require_dance_studio_owner, only: %i[new create index]
  before_action :set_costume, except: %i[new create index]
  before_action :require_costume_ownership, only: %i[show]
  before_action :require_studio_costume, except: %i[new create index show]
  before_action :set_season_costume_assignments, only: %i[assign_costume edit_season_assignments]
  before_action :set_shared_info, only: %i[edit_season_assignments]
  before_action :fetch_shared_assignment_info, only: %i[create assign]

  # Studio
  # Displays all of a dance studio's costumes pictures/descriptions
  # GET /dance_studios/:dance_studio_id/costumes
  def index
    @costumes = current_user.costumes
  end

  # Studio & Dancer
  # Displays an individual costume info
  # GET /costumes/:id
  def show; end

  # Studio
  # Displays form for a dance studio to create a new costume
  # GET /dance_studios/:dance_studio_id/costumes/new
  def new
    @costume = Costume.new(dance_studio_id: params[:dance_studio_id])
    # instanstiates an empty instance of costume assignment - to collect the shared data for the assignments
    @assignment_info = @costume.build_shared_assignment_info
    # instanstiates an instance of costume assignment for each current dancer w/ the dancer's id
    @costume.build_assignments_with_dancer_id(current_user)
  end

  # Studio
  # Displays form for a dance studio to edit a costume's info
  # GET /costumes/:id/edit
  def edit; end

  # Studio
  # Receives data from new form
  # POST /dance_studios/:dance_studio_id/costumes
  def create
    # params[:costume] -> {"dance_studio_id"=>"1", top_description"=>"", "bottoms_description"=>"", "onepiece_description"=>"nvkdsn;kbv", "hair_accessory"=>"none", "picture"=>"", "costume_assignments_attributes"=>{"0"=>{"dance_season"=>"2020", "song_name"=>"test", "genre"=>"lyrical", "shoe"=>"none", "tight"=>"none"}, "7"=>{"dancer_id"=>"1", "costume_size"=>"S"}, "8"=>{"dancer_id"=>"2", "costume_size"=>"M"}, "9"=>{"dancer_id"=>"3", "costume_size"=>"M"}, "10"=>{"dancer_id"=>"0", "costume_size"=>""}, "11"=>{"dancer_id"=>"0", "costume_size"=>""}}} permitted: false>
    # params[:costume][:costume_assignments_attributes] -> {"0"=>{"dance_season"=>"2020", "song_name"=>"test", "genre"=>"lyrical", "shoe"=>"none", "tight"=>"none"}, "7"=>{"dancer_id"=>"1", "costume_size"=>"S"}, "8"=>{"dancer_id"=>"2", "costume_size"=>"M"}, "9"=>{"dancer_id"=>"3", "costume_size"=>"M"}, "10"=>{"dancer_id"=>"0", "costume_size"=>""}, "11"=>{"dancer_id"=>"0", "costume_size"=>""}} permitted: false>
    @costume = Costume.new(costume_params)
    # redirect to new costume form if costume validation error(s)
    return redirect_to_new_costume_form(danger: "Creation failure: #{@costume.errors.full_messages.to_sentence}") unless @costume.save

    ## costume saved - check if assigning costume
    # check if not assigning costume - all shared assignment info fields empty
    redirect_to_costume_path_if_not_assigning and return
    ## assigning costume - validate assignment(s)
    # check if the dance_season or song_name value is empty
    redirect_to_new_costume_form_if_required_fields_empty and return
    # check if dancer info empty
    redirect_to_new_costume_form_if_assignment_incomplete and return
    # valid assignment(s)
    redirect_to_costume_path('Costume Successfully Created & Assigned!')
  end

  # Studio
  # Receives data from edit form
  # PATCH/PUT /costumes/:id
  def update
    return render :edit unless @costume.update(costume_params)

    redirect_to_costume_path('Costume Updated!')
  end

  # Studio
  # Deletes a costume and all associated costume assignments
  # DELETE /costumes/:id
  def destroy
    @costume.destroy

    redirect_to dance_studio_costumes_path(current_user), success: 'Costume Deleted'
  end

  # Studio
  # Displays form for a dance studio to assign a costume for a season
  # GET /costumes/:id/assign
  def assign_costume
    # get info to display if previously assigned
    @shared_info = @assignments.first
    # build an empty costume assignment to collect shared info
    @assignment_info = @costume.build_shared_assignment_info
    # build costume assignments w/ dancer_id to collect each dancer's info
    @costume.build_assignments_with_dancer_id(current_user)
  end

  # Studio
  # Receives data from assign costume form
  # POST /costumes/:id/assign
  def assign
    @previous_assignment_count = @costume.costume_assignments.count # gets no. of assignments before updating
    # check if the dance_season or song_name value is empty
    redirect_to_assign_costume_form_if_required_fields_empty and return
    # try to persist to db
    @updated = @costume.update(costume_params)
    # check that if updates, @costume.costume_assignments.count is now greater than count
    redirect_to_assign_costume_form_if_assignment_incomplete and return
    # redirect if updated correctly
    redirect_to_season_assignments_path_if_updated and return
    # redirect if costume assignments are invalid
    redirect_to assign_costume_path(@costume), danger: "Assignment failure: #{@costume.errors.full_messages.to_sentence}"
  end

  # Studio
  # Displays form for a dance studio to edit a costume's assignments for a season
  # params[:season]
  # GET /costumes/:id/edit_season_assignments
  def edit_season_assignments
    @costume.build_assignments_unless_exists(current_user, @assignments)
  end

  # Studio
  # Receives info from edit_season_assignments form
  # PATCH/PUT /costumes/:id/edit_season_assignments
  def update_season_assignments
    @costume.update(costume_params)

    redirect_to season_assignments_path(@costume, season: costume_assignments_attributes.values[0].values[0])
  end

  private

  # before_action only: %i[show]
  # checks if costume belongs to studio or assigned to dancer
  def require_costume_ownership
    redirect_to root_path(message: 'Only can owner or assigned dancer can access') unless current_user.costumes.include?(@costume)
  end

  # before_action only: %i[create assign]
  # gets shared assignment info to check if assigning / validate assignments
  def fetch_shared_assignment_info
    if costume_assignments_attributes.nil?
      # studio doesn't have any current dancers
      @assignment_info = {'dance_season'=>'', 'song_name'=>'', 'genre'=>'', 'hair_accessory'=>'', 'shoe'=>'', 'tight'=>''}
    else
      @assignment_info = costume_assignments_attributes.permit!.to_h.first.pop
      # => {"dance_season"=>"", "song_name"=>"", "genre"=>"", "hair_accessory"=>"", "shoe"=>"", "tight"=>""}
      @dance_season_empty = @assignment_info[:dance_season].empty?
      @song_name_empty = @assignment_info[:song_name].empty?
    end
  end

  def costume_assignments_attributes
    params[:costume][:costume_assignments_attributes]
  end

  # create & update helper
  # redirects to costume show page with message
  def redirect_to_costume_path(message)
    redirect_to costume_path(@costume), success: message
  end

  ## create action helpers
  # redirects to new costume form with message
  def redirect_to_new_costume_form(message)
    redirect_to new_dance_studio_costume_path(current_user.id), message
  end

  # redirects to costume show page if not assigning the new costume
  # checks if all shared assignment info fields are empty
  def redirect_to_costume_path_if_not_assigning
    redirect_to_costume_path('Costume Successfully Created!') if @assignment_info.values.all?('')
  end

  # redirects to new costume form if assigning costume & has shared info errors
  # checks if either the dance_season or song_name value is empty
  def redirect_to_new_costume_form_if_required_fields_empty
    redirect_to new_dance_studio_costume_path(current_user.id), danger: 'Must fill out Dance Season & Song Name AND select at least 1 dancer w/ costume size & costume condition' if @dance_season_empty || @song_name_empty
  end

  # redirects to new costume form if assigning costume & has dancer info errors
  # checks if dancer info empty
  def redirect_to_new_costume_form_if_assignment_incomplete
    redirect_to_new_costume_form(danger: 'Must select at least 1 dancer w/ costume size & costume condition') if @costume.costume_assignments.empty?
  end

  ## assign action helper
  # redirects to assign costume form if has shared info errors
  # checks if either the dance_season or song_name value is empty
  def redirect_to_assign_costume_form_if_required_fields_empty
    if @costume.costume_assignments.empty?
      redirect_to assign_costume_path(@costume), danger: 'Assignment failure: Must fill out Dance Season & Song Name AND select at least 1 dancer w/ costume size & costume condition' if @dance_season_empty || @song_name_empty
    else # if costume has been previously assigned
      redirect_to assign_costume_path(@costume, season: @costume.costume_assignments.last.dance_season), danger: 'Assignment failure: Must fill out Dance Season & Song Name AND select at least 1 dancer w/ costume size & costume condition' if @dance_season_empty || @song_name_empty
    end
  end

  # redirects to costume season_assignments page if assignments updated
  def redirect_to_season_assignments_path_if_updated
    redirect_to season_assignments_path(@costume, season: @costume.costume_assignments.last.dance_season) if @updated
  end

  # redirects to assign costume form if assignments have dancer info errors
  # checks if @costume.costume_assignments.count is greater than previous_assignment_count
  def redirect_to_assign_costume_form_if_assignment_incomplete
    redirect_to assign_costume_path(@costume), danger: 'Assignment failure: Must also select at least 1 dancer w/ costume size & costume condition' if @updated && @previous_assignment_count == @costume.costume_assignments.count
  end

  def costume_params

app/helpers/costumes_helper.rb
module CostumesHelper
  # return true if @costume has no rows w/ 2020 dance season in CostumeAssignments table
  def unassigned?
    current_user.unassigned_studio_costumes.include?(@costume)
  end

  def set_costume_path(costume, season)
    season ? costume_path(costume, season: season) : costume_path(costume)
  end

  def costume_picture?(costume)
    costume.picture.present?
  end

  def costume_onepiece_description?(costume)
    costume.onepiece_description.present?
  end

  def show_costume_with_link(costume, path)
    if costume_picture?(costume)
      link_to image_tag(costume.picture, width: 100), path
    elsif costume_onepiece_description?(costume)
      link_to costume.onepiece_description, path
    else
      link_to costume.twopiece_description, path
    end
  end

  def assign_costume_button(costume)
    # if previously assigned, pass the last season the costume was assigned
    link_to_if costume.seasons.empty?, 'Assign Costume', assign_costume_path(costume), class: 'button is-success is-light' do |name|
      link_to name, assign_costume_path(costume, season: costume.seasons.to_a.pop[0]), class: 'button is-success is-light'
    end
  end

  def view_costume_assignments_button(costume)
    if params[:season]
      link_to "View #{current_year} Costume Assignments", season_assignments_path(costume, season: current_year), class: 'button is-primary'
    else
      link_to 'View All Costume Assignments', assigned_costume_path(costume), class: 'button is-primary'
    end
  end

  def costume_seasons(costume)
    costume.seasons
  end

  def studio_has_current_dancers?
    current_user.dancers.current_dancers.present? 
  end

  def collecting_shared_info?(assignment_builder)
    assignment_builder.object.dancer_id.nil?
  end

  def collecting_dancer_info?(assignment_builder)
    !assignment_builder.object.dancer_id.nil? && assignment_builder.object.dance_season.nil?
  end

  def displaying_assigned_dancers?(assignment_builder)
    !assignment_builder.object.dancer_id.nil? && assignment_builder.object.dance_season == @season
  end

  def adding_dancers?(assignment_builder)
    assignment_builder.object.dance_season.nil?
  end

  # only display ADD DANCER(S) if there are more dancers to assign
  def any_dancers_to_assign?(assignments)
    assignments.count != current_user.dancers.current_dancers.count
  end
end

app/views/costumes/_create_rows.erb
<% if @count.multiple_of?(6) %>
    </div>
  </div>
  <div class='columns is-desktop'>
    <div class='column is-2 is-narrow-desktop'>
<% end %>

app/views/costumes/_dancer_table.erb
<div class='table-container'>
  <table class='table is-narrow is-striped is-hoverable'>
    <thead class='has-text-weight-bold'>
      <tr>
        <td>Dancer Name</td>
        <td>Costume Size</td>
        <td>Costume Condition</td>
      </tr>
    </thead>
    <tbody>
      <% @assignments.each do |assignment| %>
      <tr>
        <td><%= full_name(assignment.dancer) %></td>
        <td><%= assignment.costume_size %></td>
        <td><%= assignment.costume_condition %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/costumes/_display.erb
<div class='container is-fluid has-text-centered'>
  <div class='columns is-desktop'>
    <% @count = 0 %>
    <% @costumes.each do |costume| %>
      <% costume_path = set_costume_path(costume, @season) %>
      <div class='column is-2 is-narrow-desktop'>
        <%= render 'costumes/create_rows' %>
        <div class='box'>
          <%= show_costume_with_link(costume, costume_path) %>
        </div>
      </div>
      <% @count += 1 %>
    <% end %>
  </div>
</div>

app/views/costumes/_display_shared_assignment_info.erb
<div class='columns has-text-grey has-text-centered'>
  <!-- Genre -->
  <div class='column'>
    <h2 class='title heading is-size-5'>Genre</h2>
    <%= @shared_info.genre %>
  </div>
  <!-- hair accessory -->
  <div class='column'>
    <h2 class='title heading is-size-5'>Hair Accessory</h2>
    <%= @shared_info.hair_accessory %>
  </div>
  <!-- Shoes -->
  <div class='column'>
    <h2 class='title heading is-size-5'>Shoes</h2>
    <%= @shared_info.shoe %>
  </div>
  <!-- Tights -->
  <div class='column'>
    <h2 class='title heading is-size-5'>Tights</h2>
    <%= @shared_info.tight %>
  </div>
</div>

app/views/costumes/_picture.erb
<% if costume_picture?(@costume) %>
  <%= image_tag @costume.picture, width: 200 %>
<% elsif costume_onepiece_description?(@costume) %>
  <%= @costume.onepiece_description %>
<% else %>
  <%= @costume.twopiece_description %>
<% end %>

app/views/costumes/_studio_controls.erb
<!-- If assigned, display no. of dancers by season -->
<% if costume_seasons(@costume).present? %>
  <div class='columns'>
    <div class='column is-narrow'>
      <div class='box'>
        <table class='table'>
          <thead>
            <tr>
              <td><h2 class='subtitle'>Season</h2></td>
              <td><h2 class='subtitle'>Dancers</h2></td>
            </tr>
          </thead>
          <tbody>
            <!-- {"2019"=>3, "2020"=>3} -->
            <% costume_seasons(@costume).each do |season| %>
              <tr>
                <td><%= season[0] %></td>
                <td><%= season[1] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>
<!-- View Current / All Costume Assignments & Assign Costume -->
<div class='buttons is-grouped'>
  <!-- View Current Costume Assignments / View All Costume Assignments -->
  <%= view_costume_assignments_button(@costume) %>
  <!-- Assign an Unassigned Costume -->
  <% if unassigned? && current_user.dancers.current_dancers.present? %>
    <%= assign_costume_button(@costume) %>
  <% end %>
</div>
<!-- Edit / Delete Costume -->
<div class='buttons is-grouped'>
  <%= link_to 'Edit Costume', edit_costume_path(@costume), class: 'button is-warning' %>
  <%= link_to 'Delete Costume', costume_path(@costume), class: 'button is-danger', method: :delete %>
</div>

app/views/costumes/assign_costume.erb
<% if studio_has_current_dancers? %>
  <div class='content has-text-centered'>
    <h1 class='title has-text-primary'>Assign Costume Form</h1>
    <!-- Costume Picture -->
    <%= render 'picture' %>
  </div>
  <div class='box'>
    <!-- if previously assigned, display shared assignment info -->
    <% if @season.present? %>
      <div class='box'>
        <h2 class='subtitle is-size-4 has-text-centered'>Last Assigned in <%= @season %></h2>
        <%= render 'display_shared_assignment_info'%>
      </div>
    <% end %>
    <!-- Costume Assignment Form -->
    <%= form_with model: @costume, url: assign_path, method: :post, local: true do |f| %>
      <!-- Shared Assignment info -->
      <div class='box'>
        <h2 class='subtitle'>Enter Costume Assignment Details</h2>
        <%= f.fields_for :costume_assignments do |assignment_builder| %>
          <% if collecting_shared_info?(assignment_builder) %>
            <!-- Dance Season -->
            <div class='field'>
              <%= assignment_builder.label :dance_season, class: 'label is-capitalized' %>
              <div class='control'>
                <%= assignment_builder.text_field :dance_season, class:'input is-danger', placeholder: 'e.g. 2020' %>
                <p class='help is-danger'>Required</p>
              </div>
            </div>
            <!-- Song Name -->
            <div class='field'>
              <%= assignment_builder.label :song_name, class: 'label is-capitalized' %>
              <div class='control'>
                <%= assignment_builder.text_field :song_name, class:'input is-danger' %>
                  <p class='help is-danger'>Required</p>
              </div>
            </div>
            <!-- Genre -->
            <div class='field'>
              <%= assignment_builder.label :genre, class: 'label' %>
              <div class='control'>
                <%= assignment_builder.text_field :genre, class:'input', placeholder: 'e.g. tap, jazz, lyrical, etc.' %>
              </div>
            </div>
            <!-- Hair Accessory -->
            <div class='field'>
              <%= assignment_builder.label :hair_accessory, class: 'label is-capitalized' %>
              <div class='control'>
                <%= assignment_builder.text_field :hair_accessory, class:'input', placeholder: "Enter description or 'none'" %>
              </div>
            </div>
            <!-- Shoes -->
            <div class='field'>
              <%= assignment_builder.label :shoe, 'Shoes', class: 'label' %>
              <div class='control'>
                <%= assignment_builder.text_field :shoe, class:'input', placeholder: "If no shoes, enter 'none'" %>
              </div>
            </div>
            <!-- Tights -->
            <div class='field'>
              <%= assignment_builder.label :tight, 'Tights', class: 'label' %>
              <!--label class="label" for="costume_costume_assignments_attributes_0_tight">Tight</label-->
              <div class='control'>
                <%= assignment_builder.text_field :tight, class:'input', placeholder: "If no tights, enter 'none'" %>
                <!--input class="input" type="text" name="costume[costume_assignments_attributes][0][tight]" id="costume_costume_assignments_attributes_0_tight"-->
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <!-- if previously assigned, display previous assigned dancer info -->
      <% if @season.present? %>
        <div class='box'>
          <h2 class='subtitle is-4 has-text-centered'><%= @assignments.count %> Costumes Assigned in <%= @season %></h2>
          <div class='content has-text-centered'>
            <%= render 'dancer_table'%>
          </div>
        </div>
      <% end %>
      <!-- Dancer(s), Costume Size & Condition -->
      <div class='box'>
        <h2 class='subtitle'>Select Dancer(s)
          <p class='help is-danger'>Must select at least 1 dancer w/ costume size & costume condition</p>
        </h2>
        <div class='columns is-desktop'>
          <% @count = 0 %>
          <%= f.fields_for :costume_assignments do |assignment_builder| %>
            <% if collecting_dancer_info?(assignment_builder) %>
              <div class='column is-2'>
                <!-- create rows -->
                <%= render 'create_rows' %>
                <!-- Dancer -->
                <div class='field'>
                  <div class='control'>
                    <%= assignment_builder.check_box :dancer_id, {:checked => false, class: 'checkbox'}, assignment_builder.object.dancer_id, "0" %>
                    <!--input name="costume[costume_assignments_attributes][7][dancer_id]" type="hidden" value="0"-->
                    <!--input class="checkbox" type="checkbox" value="1" name="costume[costume_assignments_attributes][7][dancer_id]" id="costume_costume_assignments_attributes_7_dancer_id"-->
                    <!-- next dancer -->
                    <!--input name="costume[costume_assignments_attributes][8][dancer_id]" type="hidden" value="0"-->
                    <!--input class="checkbox" type="checkbox" value="2" name="costume[costume_assignments_attributes][8][dancer_id]" id="costume_costume_assignments_attributes_8_dancer_id"-->
                    <%= assignment_builder.label full_name(assignment_builder.object.dancer),  full_name(assignment_builder.object.dancer), class: 'checkbox has-text-weight-bold' %>
                    <!--label class="checkbox" for="costume_costume_assignments_attributes_7_Madelyn Berrier">Madelyn Berrier</label-->              
                  </div>
                </div>   
                <!-- Costume Size -->
                <div class='field'>
                  <%= assignment_builder.label :costume_size, class: 'label is-size-7 is-capitalized' %>
                  <div class='control'>
                    <div class='select is-small'>
                      <%= assignment_builder.select(:costume_size, options_for_select([['XS', 'XS'], ['S', 'S'], ['M', 'M'], ['L', 'L']]), {prompt: "Select Size"}) %>
                    </div>
                  </div>
                </div>
                <!-- Costume Condition -->
                <div class='field'>
                  <%= assignment_builder.label :costume_condition, class: 'label is-size-7 is-capitalized' %>
                  <div class='control'>
                    <div class='select is-small'>
                      <%= assignment_builder.select(:costume_condition, options_for_select([['Select Condition', ""], ['New', 'New'], ['Used', 'Used']])) %>
                    </div>
                  </div>
                </div>
              </div>
              <% @count += 1 %>
            <% end %>
          <% end %>
        </div>
      </div>
      <!-- submit button -->
      <div class='field'>
        <div class='control'>
          <%= f.submit 'Assign Costume', class: 'button is-primary' %>
        </div>
      </div>
    <% end %>
  </div>
  <!-- cancel button -->
  <%= cancel_button(unassigned_costumes_path(current_user)) %>
<% else %>
  <div class='content has-text-centered'>
    <h1 class='title has-text-primary'>Need Current Dancers to Assign Costume</h1>
  </div>
<% end %>

app/views/costumes/costume_assignments.erb
<div class='content has-text-centered'>
  <!-- Costume Picture/description -->
  <figure class='is-128x128'>
    <%= render 'picture' %>
  </figure>
  <!-- if costume assignment(s) exist, render table -->
  <% if @assignments.exists? %>
    <%= render 'costume_assignments/table' %>
  <% else %>
    <h2 class='subtitle'>No Assignments</h2>
  <% end %>
</div>

app/views/costumes/index.erb
<div class='content has-text-centered'>
  <h1 class='title has-text-primary'><%= current_user.studio_name %> Costumes</h1>
  <%= render 'display' %>
</div>

app/views/costumes/season_assignments.erb
<div class='content has-text-centered'>
  <!-- Song Name -->
  <h1 class='title has-text-primary'><%= @assignments.first.song_name%></h1>
  <!-- Dance Season -->
  <h2 class='subtitle'><%= @season %></h2>
  <!-- Costume Picture -->
  <%= render 'picture' %>
  <!-- Shared Assignment Info -->
  <div class='box'>
    <%= render 'display_shared_assignment_info'%>
  </div>
  <!-- Dancer(s), Costume Size & Costume Condition -->
  <div class='box'>
    <%= render 'dancer_table'%>
  </div>
</div>
<!-- Edit Button -->
<%= link_to 'Edit', edit_season_assignments_path(@costume, season: @season), class: 'button is-warning'%>
<!-- Delete Button -->
<%= link_to 'Delete', season_assignments_path(@costume, season: @season), class: 'button is-danger', method: :delete %>

app/views/costumes/show.erb
<section class='section'>
  <div class='columns'>
    <div class='column'>
      <!-- Costume Picture -->
      <%= render 'picture' %>
    </div>
    <!-- Two Piece Costume -->
    <% if !costume_onepiece_description?(@costume) %>
      <!-- Top -->
      <div class='column'>
        <div class='box'>
          <h2 class='title is-4'>Top</h2>
          <%= @costume.top_description %>
        </div>
      </div>
      <!-- Bottoms -->
      <div class='column'>
        <div class='box'>
          <h2 class='title is-4'>Bottoms</h2>
          <%= @costume.bottoms_description %>
        </div>
      </div>
    <% else %>
      <!-- One-Piece Costume -->
      <div class='column'>
        <div class='box'>
          <h2 class='title is-4'>One-Piece</h2>
          <%= @costume.onepiece_description %>
        </div>
      </div>
    <% end %>
  </div>
  <% if owner? %>
    <%= render 'studio_controls' %>
  <% end %>
</section>