config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Root route
  root 'application#home'

  # Shallow nested routes, nests: index create new
  resources :dance_studios, except: %i[new index], shallow: true do
    resources :costumes
    resources :dancers, except: %i[create]
    resources :costume_assignments, only: %i[index]
    # Route for dance studio to view their current dancers
    get '/dancers/current_dancers' => 'dancers#current_dancers', as: 'current_dancers'
  end

  post '/dancers' => 'dancers#create'

  # Routes for a dancer
  scope '/dancers/:id' do
    # Route for dancers to view all their costume assignments
    get '/costume_assignments' => 'dancers#dancer_assignments', as: 'dancer_costumes'
    # Route for dancer to view their current costume asignments
    get '/current_assignments' => 'dancers#current_assignments', as: 'dancer_current_assignments'
  end

  # Routes for a dance studio
  scope '/dance_studios/:id' do
    # Route for dance studio to search for costume(s)
    get '/search' => 'dance_studios#search', as: 'search'
    # Route for dance studio to view their current costume assignments
    get '/current_assignments' => 'dance_studios#current_assignments', as: 'studio_current_assignments'
    # Route for dance studio to view the costumes currently in use
    get '/current_costumes' => 'dance_studios#current_costumes', as: 'studio_current_costumes'
    # Route for dance studio to view the costumes not currently in use
    get '/unassigned_costumes' => 'dance_studios#unassigned_costumes', as: 'unassigned_costumes'
  end
  scope '/costumes/:id' do
    # Routes for dance studio to assign a costume to dancers
    get '/assign' => 'costumes#assign_costume', as: 'assign_costume'
    post '/assign' => 'costumes#assign'
    # Route for a dance studio to view all of a costume's assignments
    get '/assignments' => 'costume_assignments#costume_assignments', as: 'assigned_costume'
    # Route for a dance studio to view a costume's season assignments
    get '/season_assignments' => 'costume_assignments#season_assignments', as: 'season_assignments'
    # Route for a dance studio to delete a costume's season assignments
    delete '/season_assignments' => 'costume_assignments#delete_season_assignments'
    # Routes for a dance studio to edit a costume's season assignments
    get '/edit_season_assignments' => 'costumes#edit_season_assignments', as: 'edit_season_assignments'
    patch '/edit_season_assignments' => 'costumes#update_season_assignments'
    post '/edit_season_assignments' => 'costumes#update_season_assignments'
  end

  # Route for signing up a user (dance_studio & dancer)
  get '/register' => 'registrations#new'

  # Routes for logging in
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  # Routes for Google authentication
  get 'auth/google_oauth2', as: 'google_omniauth'
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('application#home')
end

# You can have the root of your site routed with "root":
# root 'welcome#index'

# Example of regular route:
# get 'products/:id' => 'catalog#view'

# Example of Custom Route:
# get "students/:id/activate" => "students#activate", as: "activate_student"

app/models/dance_studio.rb
class DanceStudio < ApplicationRecord
  # adds methods, ie: dancers, dancers<<, dancers.delete, dancers_ids=ids
  has_many :dancers, dependent: :destroy # all associated objects also destroyed
  # adds methods, ie: costumes, costumes<<, costumes.delete, costumes_ids=ids
  has_many :costumes, dependent: :destroy
  # adds methods, ie: costume_assignment_ids=ids
  has_many :costume_assignments, through: :costumes
  has_many :costume_assignments, through: :dancers

  has_secure_password

  # Verifies the email is not already in use by a dancer
  validate :email_not_taken, on: :create
  validate :email_not_taken, on: :update

  validates :password, confirmation: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :studio_name, :owner_name, :password_confirmation, presence: true

  # Omniauth - google
  def self.from_omniauth(auth)
    # Creates a new user only if it doesn't exist
    where(email: auth.info.email).first_or_initialize do |user|
      user.owner_name = auth.info.name
      user.email = auth.info.email
    end
  end

  # Checks if the email is not already used by a dancer
  def email_not_taken
    Dancer.all.each do |dancer|
      errors.add(:email, 'is taken') if dancer.email.downcase == email.downcase
    end
  end

  # Gets the current costume assignments for a dance studio
  def current_studio_assignments
    costume_assignments.current_assignments
  end

  # Gets the current costumes for a dance studio
  def current_studio_costumes
    current_studio_assignments.find_costumes
  end

  # Gets the currently unassigned costumes for a dance studio
  def unassigned_studio_costumes
    costumes.to_a.delete_if { |costume| current_studio_costumes.include?(costume) }
  end

  # Gets the dance studio's costumes that contain the search term in their description
  def search(search_term)
    costumes.where('top_description LIKE ? OR bottoms_description LIKE ? OR onepiece_description LIKE ?', "%#{search_term}%","%#{search_term}%","%#{search_term}%")
  end
end

app/controllers/dance_studios_controller.rb
class DanceStudiosController < ApplicationController
  skip_before_action :require_logged_in, only: :create
  before_action :require_studio_ownership, except: :create
  before_action :set_dance_studio, only: %i[show edit update destroy]

  # GET /dance_studios/:id
  def show; end

  # GET /dance_studios/:id/edit
  def edit; end

  # POST /dance_studios
  def create
    @dance_studio = DanceStudio.new(dance_studio_params)

    return render_registration_form unless @dance_studio.save

    log_in(@dance_studio, 'Successfully Registered!')
  end

  # PATCH/PUT /dance_studios/:id
  def update
    return render :edit unless @dance_studio.update(dance_studio_params)

    redirect_to_dance_studio_page('Account Info Updated!')
  end

  # DELETE /dance_studios/:id
  def destroy
    @dance_studio.destroy
    logout('Account Deleted!')
  end

  # Displays a dance studio's current costume assignments
  # GET /dance_studios/:id/current_assignments
  def current_assignments
    @assignments = current_user.current_studio_assignments
    @costumes = @assignments.find_costumes
    @season = @assignments.first.dance_season unless @assignments.empty?
  end

  # Displays a dance studio's current season costumes
  # GET /dance_studios/:id/current_costumes
  def current_costumes
    @costumes = current_user.current_studio_costumes
    @season = Time.now.year
  end

  # Displays a dance studio's unassigned costumes for the current season
  # GET /dance_studios/:id/unassigned_costumes
  def unassigned_costumes
    @costumes = current_user.unassigned_studio_costumes
  end

  # Displays a dance studio's costumes with the search term in their description
  # GET /dance_studios/:id/search
  def search
    @costumes = current_user.search(params[:search])
  end

  private

  # before_action except: :create
  def require_studio_ownership
    redirect_to root_path(message: 'Only dance studio owner can access') unless owner? && current_user.id == params[:id].to_i
  end

  # before_action only: %i[show edit update destroy]
  def set_dance_studio
    @dance_studio = DanceStudio.find(params[:id])
  end

  def dance_studio_params
    params.require(:dance_studio).permit(:studio_name, :owner_name, :email, :password, :password_confirmation)
  end
end

app/helpers/dance_studios_helper.rb
module DanceStudiosHelper
  def link_to_dancer_current_assignments(assignment)
    link_to full_name(Dancer.find(assignment.dancer_id)), dancer_current_assignments_path(assignment.dancer_id)
  end

  def assignment_info(costume)
    @assignments.where(costume_id: costume.id).first
  end

  def uppercase_song_name(info)
    info.song_name.upcase
  end

  def costume_match(costume, assignment)
    costume.id == assignment.costume_id
  end

  def current_year
    Time.now.year
  end
end

app/views/dance_studios/_current_assignments_table.erb
<% @costumes.each do |costume| %>
  <!-- display costume picture & assignment info -->
  <article class='media'>
    <!-- costume picture/description -->
    <figure class='media-left'>
      <p class='image is-96x96'>
        <%= show_costume_with_link(costume, season_assignments_path(costume, season: @season)) %>
      </p>
    </figure>
    <!-- get assignment info for costume -->
    <% info = assignment_info(costume) %>
    <div class='media-content'>
      <div class='content'>
        <!-- song name (genre) -->
        <p><strong><%= uppercase_song_name(info) %></strong> (<%= info.genre %>)</p>
        <!-- hair accessory, shoes, and tights -->
        <p style='margin-left:3%;'>
          <strong>Hair Accessory:</strong> <%= info.hair_accessory %> <br>
          <strong>Shoes:</strong> <%= info.shoe %> <br>
          <strong>Tights:</strong> <%= info.tight %>
        </p>
      </div>
      <!-- nested media object -->
      <article class='media'>
        <!-- empty pic to indent -->
        <figure class='media-left'>
          <p class='image is-48x48'></p>
        </figure>
        <!-- nested media content -->
        <div class='media-content'>
          <!-- table of dancer name, their costume's size, and its condition -->
          <table class='table is-narrow'>
            <thead>
              <tr>
                <th>Dancer</th>
                <th>Size</th>
                <th>Condition</th>
              </tr>
            </thead>
            <% @assignments.each do |assignment| %>
              <!-- check if assigment's costume matches the costume (current iteration) -->
              <% if costume_match(costume, assignment) %>
                <!-- display assignment info -->
                <tbody>
                  <!-- Dancer Name, costume size, costume condition -->
                  <tr>
                    <td><%= link_to_dancer_current_assignments(assignment) %></td>
                    <td><%= assignment.costume_size %></td>
                    <td><%= assignment.costume_condition %></td>
                  </tr>
                </tbody>
              <% end %><!-- end if -->
            <% end %><!-- @costume_assignments.each -->
          </table>
        </div><!-- end nested media content -->
      </article><!-- end nested media object -->
    </div><!-- end media content -->
  </article><!-- end article -->
<% end %><!-- end @costumes.each -->

app/views/dance_studios/_error_notification.erb
<% if any_validation_errors?(@dance_studio) %>
  <section class='section'>
    <div class='container is-fluid has-text-centered'>
      <div id='error_explanation' class='notification is-danger'>
        <h2>
          <%= error_count(@dance_studio) %>
          prohibited this dance studio from being saved!
        </h2>
      </div>
    </div>
  </section>
<% end %>

app/views/dance_studios/_form.erb
<!-- Validation Error(s) Notification -->
<%= render 'dance_studios/error_notification' %>
<div class='box'>
  <!-- Dance Studio Form -->
  <%= form_for @dance_studio do |f| %>
    <!-- studio name -->
    <div class='field'>
      <%= f.label :studio_name, class: 'label is-capitalized' %>
      <div class='control has-icons-left'>
        <%= f.text_field :studio_name, class:'input', placeholder: 'Enter Studio Name' %>
          <span class='icon is-small is-left'>
            <i class='fas fa-school'></i>
          </span>
      </div>
      <% if any_field_errors?(@dance_studio, :studio_name) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dance_studio, :studio_name) %></p>
      <% end %>
    </div>
    <!-- owner name -->
    <div class='field'>
      <%= f.label :owner_name, class: 'label is-capitalized' %>
      <div class='control has-icons-left'>
        <%= f.text_field :owner_name, class:'input', placeholder: 'Enter Studio Owner' %>
          <span class='icon is-small is-left'>
            <i class='fas fa-user'></i>
          </span>
      </div>
      <% if any_field_errors?(@dance_studio, :owner_name) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dance_studio, :owner_name) %></p>
      <% end %>
    </div>
    <!-- email -->
    <div class='field'>
      <%= f.label :email, class: 'label' %>
      <div class='control has-icons-left'>
        <%= f.email_field :email, class:'input', placeholder: 'Enter Email' %>
          <span class='icon is-small is-left'>
            <i class='fas fa-envelope'></i>
          </span>
      </div>
      <% if any_field_errors?(@dance_studio, :email) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dance_studio, :email) %></p>
      <% end %>
    </div>
    <!-- password -->
    <div class='field'>
      <%= f.label :password, class: 'label' %>
      <div class='control has-icons-left'>
        <%= f.password_field :password, class:'input', placeholder: 'Enter Password' %>
          <span class='icon is-small is-left'>
            <i class='fas fa-lock'></i>
          </span>
      </div>
      <% if any_field_errors?(@dance_studio, :password) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dance_studio, :password) %></p>
      <% end %>
    </div>
    <!-- password confirmation -->
    <div class='field'>
      <%= f.label :password_confirmation, class: 'label is-capitalized' %>
      <div class='control has-icons-left'>
        <%= f.password_field :password_confirmation, class:'input', placeholder: 'Re-enter Password' %>
          <span class='icon is-small is-left'>
            <i class='fas fa-lock'></i>
          </span>
      </div>
      <% if any_field_errors?(@dance_studio, :password_confirmation) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dance_studio, :password_confirmation) %></p>
      <% end %>
    </div>
    <!-- submit button -->
    <div class='field'>
      <div class='control'>
        <%= f.submit class: 'button is-primary is-capitalized' %>
      </div>
    </div>
  <% end %>
</div>

app/views/dance_studios/_search_form.erb
<%= form_with url: search_path(current_user), method: :get, local: true do %>
  <div class='field has-addons'>
    <div class='control'>
      <%= text_field_tag :search, params[:search], class: 'input', placeholder: 'costume keyword' %>
    </div>
    <div class='control'>
      <%= submit_tag 'Search', name: nil, class: 'button has-text-grey-dark' %>
    </div>
  </div>
<% end%>

app/views/dance_studios/current_assignments.erb
<div class='content has-text-centered'>
  <h1 class='title has-text-primary'><%= @season %> Costume Assignments</h1>
  <!-- if dance studio has current costume assignments, render table -->
  <% if @assignments.exists? %>
    <%= render 'current_assignments_table' %>
  <% else %>
    <h2 class='subtitle'>No Costume Assignments For This Season</h2>
  <% end %>
</div>

app/views/dance_studios/current_costumes.erb
<div class='content has-text-centered'>
  <h1 class='title has-text-primary'><%= current_year %> Season Costumes</h1>
  <%= render 'costumes/display' %>
</div>

app/views/dance_studios/edit.erb
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
<div class='content has-text-centered'>
  <h1 class='title has-text-primary'>Update <%= current_user.studio_name %>'s Account Info</h1>
  <h3 class='subtitle is-size-6 has-text-danger'><u>Must enter password AND password confirmation to make changes</u></h3>
</div>
<%= render 'form' %>
<%= cancel_button(dance_studio_path(current_user)) %>

app/views/dance_studios/search.erb
<div class='content has-text-centered'>
  <h1 class='title has-text-primary'>Search Results</h1>
  <!-- if costume(s) found, render display -->
  <% if @costumes.exists? %>
    <%= render 'costumes/display' %>
  <% else %>
    <h2 class='subtitle'>No Costumes Found</h2>
  <% end %>
</div>

app/views/dance_studios/show.erb
<div class='content has-text-centered'>
  <h1 class='title heading is-1 has-text-primary'><%= current_user.studio_name %></h1>
  <h2 class='subtitle is-3'><%= current_user.owner_name %></h2>
</div>
<!-- Costumes -->
<div class='box'>
  <div class=content>
    <h2 class='heading is-size-5'>Costumes</h2>
  </div>
  <div class='buttons'>
    <%= link_to 'Create New Costume', new_dance_studio_costume_path(current_user), class: 'button is-link is-light' %>
    <%= link_to 'View All Costumes', dance_studio_costumes_path(current_user), class: 'button is-link is-light' %>
    <%= link_to 'Current Season Costumes', studio_current_costumes_path(current_user), class: 'button is-link is-light' %>
    <%= link_to 'Unassigned Costumes', unassigned_costumes_path(current_user), class: 'button is-link is-light' %>
  </div>
<!-- Costume Assignments -->
</div>
  <div class='box'>
    <div class=content>
      <h2 class='heading is-size-5'>Costume Assignments</h2>
    </div>
    <div class='buttons'>
    <%= link_to 'Current Costume Assignments', studio_current_assignments_path(current_user), class: 'button is-primary is-light' %>
    <%= link_to 'All Costume Assignments', dance_studio_costume_assignments_path(current_user), class: 'button is-primary is-light' %>
  </div>
</div>
<!-- Dancers -->
<div class='box'>
  <div class=content>
    <h2 class='heading is-size-5'>Dancers</h2>
  </div>
  <div class='buttons'>
    <%= link_to 'All My Dancers', dance_studio_dancers_path(current_user), class: 'button is-success is-light' %>
    <%= link_to 'Current Dancers', dance_studio_current_dancers_path(current_user), class: 'button is-success is-light' %>
    <%= link_to 'Add New Dancer', new_dance_studio_dancer_path(current_user), class: 'button is-success is-light' %>
  </div>
</div>
<!-- Account -->
<div class='box'>
  <div class=content>
    <h2 class='heading is-size-5'>Account</h2>
  </div>
  <div class='buttons'>
    <%= link_to 'Edit Account Info', edit_dance_studio_path(current_user), class: 'button is-warning is-light' %>
    <%= link_to 'Delete Account', dance_studio_path(current_user), method: :delete, class: 'button is-danger is-light' %>
  </div>
</div>

app/views/dance_studios/unassigned_costumes.erb
<div class='content has-text-centered'>
  <h1 class='title has-text-primary'>Unassigned <%= current_year %> Season Costumes</h1>
  <%= render 'costumes/display' %>
</div>