config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Root route
  root 'application#home'

  # Shallow nested routes, nests: index create new
  resources :dance_studios, except: %i[new index], shallow: true do
    resources :costumes
    resources :dancers, except: %i[create]
    resources :costume_assignments, only: %i[index]
    # Route for dance studio to view their current dancers
    get '/dancers/current_dancers' => 'dancers#current_dancers', as: 'current_dancers'
  end

  post '/dancers' => 'dancers#create'

  # Routes for a dancer
  scope '/dancers/:id' do
    # Route for dancers to view all their costume assignments
    get '/costume_assignments' => 'dancers#dancer_assignments', as: 'dancer_costumes'
    # Route for dancer to view their current costume asignments
    get '/current_assignments' => 'dancers#current_assignments', as: 'dancer_current_assignments'
  end

  # Routes for a dance studio
  scope '/dance_studios/:id' do
    # Route for dance studio to search for costume(s)
    get '/search' => 'dance_studios#search', as: 'search'
    # Route for dance studio to view their current costume assignments
    get '/current_assignments' => 'dance_studios#current_assignments', as: 'studio_current_assignments'
    # Route for dance studio to view the costumes currently in use
    get '/current_costumes' => 'dance_studios#current_costumes', as: 'studio_current_costumes'
    # Route for dance studio to view the costumes not currently in use
    get '/unassigned_costumes' => 'dance_studios#unassigned_costumes', as: 'unassigned_costumes'
  end
  scope '/costumes/:id' do
    # Routes for dance studio to assign a costume to dancers
    get '/assign' => 'costumes#assign_costume', as: 'assign_costume'
    post '/assign' => 'costumes#assign'
    # Route for a dance studio to view all of a costume's assignments
    get '/assignments' => 'costume_assignments#costume_assignments', as: 'assigned_costume'
    # Route for a dance studio to view a costume's season assignments
    get '/season_assignments' => 'costume_assignments#season_assignments', as: 'season_assignments'
    # Route for a dance studio to delete a costume's season assignments
    delete '/season_assignments' => 'costume_assignments#delete_season_assignments'
    # Routes for a dance studio to edit a costume's season assignments
    get '/edit_season_assignments' => 'costumes#edit_season_assignments', as: 'edit_season_assignments'
    patch '/edit_season_assignments' => 'costumes#update_season_assignments'
    post '/edit_season_assignments' => 'costumes#update_season_assignments'
  end

  # Route for signing up a user (dance_studio & dancer)
  get '/register' => 'registrations#new'

  # Routes for logging in
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  # Routes for Google authentication
  get 'auth/google_oauth2', as: 'google_omniauth'
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('application#home')
end

# You can have the root of your site routed with "root":
# root 'welcome#index'

# Example of regular route:
# get 'products/:id' => 'catalog#view'

# Example of Custom Route:
# get "students/:id/activate" => "students#activate", as: "activate_student"

app/models/dancer.rb
class Dancer < ApplicationRecord
  belongs_to :dance_studio
  has_many :costume_assignments
  has_many :costumes, through: :costume_assignments

  has_secure_password

  # Verifies the email is not already in use by a dance studio
  validate :email_not_taken, on: :create
  validate :email_not_taken, on: :update

  validates :password, confirmation: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :first_name, :last_name, :password_confirmation, presence: true

  # Gets current dancers for a dance studio
  scope :current_dancers, -> { where(current_dancer: 1) }

  # OmniAuth - Google
  def self.from_omniauth(auth)
    # Creates a new user only if it doesn't exist
    where(email: auth.info.email).first_or_initialize do |user|
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end

  # Checks if the email is not already used by a dance studio
  def email_not_taken
    DanceStudio.all.each do |studio|
      errors.add(:email, 'is taken') if studio.email.downcase == email.downcase
    end
  end
end

app/controllers/dancers_controller.rb
class DancersController < ApplicationController
  skip_before_action :require_logged_in, only: :create
  before_action :require_dance_studio_owner, only: %i[new index current_dancers]
  before_action :set_dancer, except: %i[new create index current_dancers]
  before_action :require_studio_dancer, except: %i[new create index current_dancers]

  # Studio
  # Displays all dancers for a dance studio
  # GET /dance_studios/:dance_studio_id/dancers
  def index
    @dancers = current_user.dancers.order(:last_name, :first_name)
  end

  # Dancer & Studio
  # Display dancer's show page
  # GET /dancers/:id
  def show; end

  # Studio
  # Displays form for a dance studio to create a new dancer
  # GET /dance_studios/:dance_studio_id/dancers/new
  def new
    @dancer = Dancer.new(dance_studio_id: current_user.id, password: 'password', password_confirmation: 'password')
  end

  # Dancer
  # Displays form to edit dancer's account info
  # GET /dancers/:id/edit
  def edit; end

  # Dancer & Studio
  # Dancer: receives data from registrations/new (renders dancers/_form)
  # Dance Studio: receives data from dancers/new (renders _form)
  # POST /dancers
  def create
    @dancer = Dancer.new(dancer_params)
    @saved = @dancer.save

    redirect_studio_if_saved && return

    log_in_dancer_if_saved && return

    return render :new if owner?

    render_registration_form
  end

  # Dancer
  # Receives data from edit form
  # PATCH/PUT /dancers/:id
  def update
    return render :edit unless @dancer.update(dancer_params)

    redirect_to dancer_path(@dancer), success: 'Account Info Updated!'
  end

  # Dancer & Studio
  # Deactivates dancer's account to keep costume assignment data
  # DELETE /dancers/:id
  def destroy
    # set current_dancer to false & password/confirmation to 'dancer'
    @dancer.update(current_dancer: false, password: 'dancer', password_confirmation: 'dancer')

    return redirect_to_dance_studio_page('Account Deactivated') unless dancer?

    logout('Account Deactivated!')
  end

  # Dancer & Studio
  # Displays all of dancer's costume assignments
  # GET /dancers/:id/costume_assignments
  def dancer_assignments
    @assignments = CostumeAssignment.where(dancer_id: @dancer).order(dance_season: :desc, genre: :asc, song_name: :asc)
  end

  # Dancer & Studio
  # Displays dancer's current costume assignments with costume picture
  # GET /dancers/:id/current_assignments
  def current_assignments
    @assignments = @dancer.costume_assignments.current_assignments
  end

  # Studio
  # Displays the current dancers for a dance studio
  # GET /dance_studios/:dance_studio_id/dancers/current_dancers
  def current_dancers
    @dancers = current_user.dancers.current_dancers.order(:last_name, :first_name)
  end

  private

  # before_action except: %i[new create index current_dancers]
  def set_dancer
    @dancer = Dancer.find(params[:id])
  end

  # before_action except: %i[new create index current_dancers]
  def require_studio_dancer
    if owner? # check if dancer belongs to studio
      redirect_to root_path(message: "Only the dancer's studio can access") unless current_user.dancers.include?(@dancer)
    else # check if dancer is current user
      redirect_to root_path(message: 'Denied access') unless current_user.id == params[:id].to_i
    end
  end

  ## create action helpers
  # Dance Studio successfully adding a dancer
  def redirect_studio_if_saved
    redirect_to_dance_studio_page('Dancer Added!') if @saved && owner?
  end

  # Dancer successfully registering
  def log_in_dancer_if_saved
    log_in(@dancer, 'Successfully Registered!') if @saved
  end

  def dancer_params
    params.require(:dancer).permit(:dance_studio_id, :first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/dancers_helper.rb
module DancersHelper
  # Concatenates a dancer's first and last name
  def full_name(dancer)
    dancer.first_name + ' ' + dancer.last_name
  end

  def dancer_studio_name(dancer)
    dancer.dance_studio.studio_name
  end

  def assignment_costume(assignment)
    Costume.find(assignment.costume_id)
  end

  def current?(dancer)
    dancer.current_dancer ? 'YES' : 'NO'
  end

  def current_assignments_count(dancer)
    dancer.costume_assignments.current_assignments.count
  end

  def all_assignments_count(dancer)
    dancer.costume_assignments.count
  end

  def current_studio_costumes_count
    current_user.current_studio_costumes.count
  end

  def costumes_count(user_type)
    user_type.costumes.count
  end
end

app/views/dancers/_current_assignments_table.erb
<div class='table-container'>
  <table class='table is-fullwidth is-striped is-hoverable'>
    <thead class='has-text-weight-bold'>
      <td>Costume</td>
      <td>Song Name</td>
      <td>Genre</td>
      <td>Hair Accessory</td>
      <td>Shoes</td>
      <td>Tights</td>
      <td>Size</td>
      <td>Condition</td>
    </thead>
    <tbody>
    <% @assignments.each do |assignment| %>
      <% costume = assignment_costume(assignment) %>
      <tr>
        <td><%= show_costume_with_link(costume, costume_path(costume)) %></td>
        <td><%= assignment.song_name %></td>
        <td><%= assignment.genre %></td>
        <td><%= assignment.hair_accessory %></td>
        <td><%= assignment.shoe %></td>
        <td><%= assignment.tight %></td>
        <td><%= assignment.costume_size %></td>
        <td><%= assignment.costume_condition %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/dancers/_error_notification.erb
<% if any_validation_errors?(@dancer) %>
  <section class='section'>
    <div class='container is-fluid has-text-centered'>
      <div id='error_explanation' class='notification is-danger'>
        <h2>
          <%= error_count(@dancer) %>
          prohibited this dancer from being saved!
        </h2>
      </div>
    </div>
  </section>
<% end %>

app/views/dancers/_form.erb
<!-- Validation Error(s) Notification -->
<%= render 'dancers/error_notification' %>
<div class='box'>
  <!-- Dancer Form -->
  <%= form_for @dancer do |f| %>
    <!-- dance studio -->
    <div class='field'>
      <%= f.label :dance_studio, class: 'label is-capitalized' %>
      <div class='control has-icons-left'>
        <div class="select">
          <!-- object.collection_select(method, collection, value_method, text_method, options = {}, html_options = {}) -->
          <%= f.collection_select(:dance_studio_id, DanceStudio.all, :id, :studio_name, {prompt: "Select Your Dance Studio"}, {class: 'select'}) %>
        </div>
        <div class='icon is-small is-left'>
          <i class='fas fa-school'></i>
        </div>
      </div>
      <% if any_field_errors?(@dancer, :dance_studio) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dancer, :dance_studio) %></p>
      <% end %>
    </div>
    <!-- first name -->
    <div class='field'>
      <%= f.label :first_name, class: 'label is-capitalized' %>
      <div class='control has-icons-left'>
        <%= f.text_field :first_name, class:'input', placeholder: 'Enter First Name' %>
          <span class='icon is-small is-left'>
            <i class='fas fa-user'></i>
          </span>
      </div>
      <% if any_field_errors?(@dancer, :first_name) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dancer, :first_name) %></p>
      <% end %>
    </div>
    <!-- last name -->
    <div class='field'>
      <%= f.label :last_name, class: 'label is-capitalized' %>
      <div class='control has-icons-left'>
        <%= f.text_field :last_name, class:'input', placeholder: 'Enter Last Name' %>
          <span class='icon is-small is-left'>
            <i class='fas fa-user'></i>
          </span>
      </div>
      <% if any_field_errors?(@dancer, :last_name) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dancer, :last_name) %></p>
      <% end %>
    </div>
    <!-- email -->
    <div class='field'>
      <%= f.label :email, class: 'label' %>
      <div class='control has-icons-left'>
        <%= f.email_field :email, class:'input', placeholder: 'Enter Email' %>
          <span class='icon is-small is-left'>
            <i class='fas fa-envelope'></i>
          </span>
      </div>
      <% if any_field_errors?(@dancer, :email) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dancer, :email) %></p>
      <% end %>
    </div>
    <!-- password -->
    <div class='field'>
      <%= f.label :password, class: 'label' %>
      <div class='control has-icons-left'>
        <%= f.password_field :password, class:'input', placeholder: 'Enter Password' %>
          <span class='icon is-small is-left'>
            <i class='fas fa-lock'></i>
          </span>
      </div>
      <% if any_field_errors?(@dancer, :password) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dancer, :password) %></p>
      <% end %>
    </div>
    <!-- password confirmation -->
    <div class='field'>
      <%= f.label :password_confirmation, class: 'label is-capitalized' %>
      <div class='control has-icons-left'>
        <%= f.password_field :password_confirmation, class:'input', placeholder: 'Re-enter Password' %>
          <span class='icon is-small is-left'>
            <i class='fas fa-lock'></i>
          </span>
      </div>
      <% if any_field_errors?(@dancer, :password_confirmation) %>
        <p class='helper has-text-danger'><%= field_error_explaination(@dancer, :password_confirmation) %></p>
      <% end %>
    </div>
    <!-- submit button -->
    <div class='field'>
      <div class='control'>
        <%= f.submit class: 'button is-primary is-capitalized' %>
      </div>
    </div>
  <% end %>
</div>

app/views/dancers/current_assignments.erb
<div class='content has-text-centered'>
  <!-- display dancer's name for dance studio owner -->
  <% if owner? %>
    <h1 class='title has-text-primary'><%= full_name(@dancer) %>'s <%= current_year %> Costume Assignments</h1>
  <% else %>
      <h1 class='title has-text-primary'><%= current_year %> Costume Assignments</h1>
  <% end %>
  <!-- if dancer has current costume assignments, render table -->
  <% if @assignments.exists? %>
    <%= render 'current_assignments_table' %>
  <% else %>
    <h2 class='subtitle'>No Assignments</h2>
  <% end %>
</div>

app/views/dancers/current_dancers.erb
<div class='content has-text-centered'>
  <h1 class='title has-text-primary'> Current Dancers at <%= current_user.studio_name %></h1>
</div>
<div class='box'>
  <!-- Table of Current Dancers -->
  <div class='table-container'>
    <table class='table is-fullwidth is-striped is-hoverable'>
      <thead class='has-text-weight-bold'>
        <td class='has-text-centered'>Dancer Name</td>
        <td class='has-text-centered'><%= current_year %> Costume Assignments</td>
        <td class='has-text-centered'>Total Costume Assignments</td>
      </thead>
      <tbody>
        <% @dancers.each do |dancer| %>
          <tr>
            <td class='has-text-centered'><%= link_to full_name(dancer), dancer_path(dancer) %></td>
            <td class='has-text-centered'><%= link_to current_assignments_count(dancer), dancer_current_assignments_path(dancer) %></td>
            <td class='has-text-centered'><%= link_to all_assignments_count(dancer), dancer_costumes_path(dancer) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- Count of Current Dancers -->
  <div class='columns'>
    <div class='column'>
      <div class='box has-text-centered'>
        <h2 class='title is-4'><%= @dancers.count %> Current Dancers</h2>
      </div>
  </div>
  <!-- Count of Current Costumes -->
  <div class='column'>
    <div class='box has-text-centered'>
      <h2 class='title is-4'><%= current_studio_costumes_count %> Current Costumes</h2>
    </div>
  </div>
</div>

app/views/dancers/dancer_assignments.erb
<div class='content has-text-centered'>
  <h1 class='title has-text-primary'><%= full_name(@dancer) %>'s Costume Assignments</h1>
  <!-- if costume assignment(s) exist, render table -->
  <% if @assignments.exists? %>
    <%= render 'costume_assignments/table' %>
  <% else %>
    <h2 class='subtitle'>No Assignments</h2>
  <% end %>
</div>

app/views/dancers/edit.erb
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
<div class='content has-text-centered'>
  <h1 class='title has-text-primary'>Update <%= full_name(@dancer) %>'s Account Info</h1>
  <h3 class='subtitle is-size-6 has-text-danger'><u>Must enter password AND password confirmation to make changes</u></h3>
</div>
<%= render 'form' %>
<%= cancel_button(dancer_path(current_user)) %>

app/views/dancers/index.erb
<div class='content has-text-centered'> 
  <h1 class='title has-text-primary'>All Dancers at <%= current_user.studio_name %></h1>
</div>
<div class='box'>
  <!-- Table of Dancers -->
  <div class='table-container'>
    <table class='table is-fullwidth is-striped is-hoverable'>
      <thead class='has-text-weight-bold'>
        <td class='has-text-centered'> Dancer Name</td>
        <td class='has-text-centered'>Current Dancer?</td>
        <td class='has-text-centered'>Total Costume Assignments</td>
      </thead>
      <tbody>
        <% @dancers.each do |dancer| %>
          <tr>
            <td class='has-text-centered'><%= link_to full_name(dancer), dancer_path(dancer) %></td>
            <td class='has-text-centered'><%= current?(dancer) %></td>
            <td class='has-text-centered'><%= link_to costumes_count(dancer), dancer_costumes_path(dancer) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- Count of Dancers -->
  <div class='columns'>
    <div class='column'>
      <div class='box has-text-centered'>
        <h2 class='title is-4'><%= @dancers.count %> Total Dancers</h2>
      </div>
  </div>
  <!-- Count of Costumes -->
  <div class='column'>
    <div class='box has-text-centered'>
      <h2 class='title is-4'><%= costumes_count(current_user) %> Total Costumes</h2>
    </div>
  </div>
</div>

app/views/dancers/new.erb
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
<!-- For a Dance Studio to create a dancer -->
<!-- Form Title -->
<h1 class='title has-text-primary has-text-centered'>Add New Dancer</h1>
<!-- Validation Error(s) Notification -->
<%= render 'error_notification' %>
<!-- New Dancer Form -->
<div class='box'>
  <%= form_for @dancer do |f| %>
    <%= f.hidden_field :dance_studio_id %>
    <%= f.hidden_field :password %>
    <%= f.hidden_field :password_confirmation %>
    <div class='box'>
      <!-- First Name -->
      <div class='field'>
        <%= f.label :first_name, class: 'label is-capitalized' %>
        <div class='control has-icons-left'>
          <%= f.text_field :first_name, class:'input', placeholder: 'Enter First Name' %>
            <span class='icon is-small is-left'>
              <i class='fas fa-user'></i>
            </span>
        </div>
        <% if any_field_errors?(@dancer, :first_name) %>
          <p class='helper has-text-danger'><%= field_error_explaination(@dancer, :first_name) %></p>
        <% end %>
      </div>
      <!-- Last Name -->
      <div class='field'>
        <%= f.label :last_name, class: 'label is-capitalized' %>
        <div class='control has-icons-left'>
          <%= f.text_field :last_name, class:'input', placeholder: 'Enter Last Name' %>
            <span class='icon is-small is-left'>
              <i class='fas fa-user'></i>
            </span>
        </div>
        <% if any_field_errors?(@dancer, :last_name) %>
          <p class='helper has-text-danger'><%= field_error_explaination(@dancer, :last_name) %></p>
        <% end %>
      </div>
      <!-- Email -->
      <div class='field'>
        <%= f.label :email, class: 'label' %>
        <div class='control has-icons-left'>
          <%= f.email_field :email, class:'input', placeholder: 'Enter Email' %>
            <span class='icon is-small is-left'>
              <i class='fas fa-envelope'></i>
            </span>
        </div>
        <% if any_field_errors?(@dancer, :email) %>
          <p class='helper has-text-danger'><%= field_error_explaination(@dancer, :email) %></p>
        <% end %>
      </div>
    <p class='help is-danger'>Must fill out all fields</p>
    </div>
    <!-- Submit Button -->
    <div class='field'>
      <div class='control'>
        <%= f.submit class: 'button is-primary' %>
      </div>
    </div>
  <% end %>
</div>
<!-- Cancel Button -->
<%= cancel_button(dance_studio_path(current_user)) %>

app/views/dancers/show.erb
<div class='content has-text-centered'>
  <h1 class='title'><%= full_name(@dancer) %></h1>
  <h2 class='subtitle heading has-text-primary'><%= dancer_studio_name(@dancer) %></h2>
</div>
<!-- Costumes -->
<div class='box'>
  <div class=content>
    <h2 class='heading is-size-5'>Costumes</h2>
  </div>
  <div class='buttons is-grouped'>
    <%= link_to 'Current Costume Assignments', dancer_current_assignments_path(@dancer), class: 'button is-link is-light' %>
    <%= link_to 'All Costumes', dancer_costumes_path(@dancer), class: 'button is-link is-light' %>
  </div>
  </div>
  <!-- Account -->
  <div class='box'>
    <div class=content>
      <h2 class='heading is-size-5'>Account</h2>
    </div>
    <div class='buttons is-grouped'>
      <% if dancer? %>
        <%= link_to 'Edit Account', edit_dancer_path(@dancer), class: 'button is-warning is-light' %>
      <% end %>
      <%= link_to 'Deactivate Account', dancer_path(@dancer), method: :delete, class: 'button is-danger is-light' %>
    </div>
  </div>
</div>